[package]
name = "energy_router"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cosmwasm-std = "0.19"
serde = { version = "1.0", features = ["derive"] }
cw20 = "0.14"

[dev-dependencies]
cosmwasm-std = { version = "0.19", features = ["test"] }
